import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('tr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      setLanguageState(savedLanguage as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const translations = {
      tr: {
        'dashboard.weeklyOverview': 'Mağaza performansınızın haftalık genel görünümü',
        'dashboard.ageDistribution': 'Yaş Dağılımı',
        'dashboard.genderDistribution': 'Cinsiyet Dağılımı',
        'dashboard.avgQueueTime': 'Ort. Kuyruk Süresi',
        'dashboard.busiestCashier': 'En Yoğun Kasa',
        'dashboard.weeklyCustomers': 'Haftalık Müşteri',
        'dashboard.dailyGenderDistribution': 'Günlük Cinsiyet Dağılımı',
        'dashboard.dailyAgeDistribution': 'Günlük Yaş Analizi',
        // Navigation
        'nav.dashboard': 'Ana Sayfa',
        'nav.customerAnalytics': 'Müşteri Analizi',
        'nav.staffManagement': 'Personel Yönetimi',
        'nav.heatmaps': 'Isı Haritaları',
        'nav.shelfOptimization': 'Rayon Optimizasyonu',
        'nav.reports': 'Raporlar',
        'nav.settings': 'Ayarlar',
        'nav.logout': 'Çıkış Yap',

        // Login
        'login.title': 'VISLIVIS',
        'login.subtitle': 'AI Destekli Perakende Analiz Platformu',
        'login.email': 'E-posta Adresi',
        'login.password': 'Şifre',
        'login.rememberMe': 'Beni Hatırla',
        'login.forgotPassword': 'Şifremi Unuttum?',
        'login.signIn': 'Panele Giriş Yap',
        'login.demoAccounts': 'Demo Hesapları:',
        'login.poweredBy': 'Gelişmiş AI ve Bilgisayarlı Görü Teknolojisi ile Desteklenmektedir',
        'login.invalidCredentials': 'Geçersiz kullanıcı adı veya şifre!',

        // Dashboard
        'dashboard.title': 'Ana Sayfa',
        'dashboard.subtitle': 'Mağaza performansınızın genel görünümü',
        'dashboard.totalCustomers': 'Toplam Müşteri',
        'dashboard.totalRevenue': 'Toplam Gelir',
        'dashboard.totalOrders': 'Toplam Sipariş',
        'dashboard.conversionRate': 'Dönüşüm Oranı',
        'dashboard.totalVisitors': 'Toplam Ziyaretçi',
        'dashboard.avgVisitDuration': 'Ort. Ziyaret Süresi',
        'dashboard.potentialLostSales': 'Potansiyel Kayıp Satış',
        'dashboard.staffActivityRate': 'Personel Aktiflik Oranı',
        'dashboard.peakHour': 'Yoğun Saat',
        'dashboard.loyaltyIndex': 'Sadakat Endeksi',
        'dashboard.today': 'Bugün',
        'dashboard.minutes': 'Dakika',
        'dashboard.dueToQueues': 'Kuyruklar nedeniyle',
        'dashboard.currentShift': 'Mevcut vardiya',
        'dashboard.visitors': 'ziyaretçi',
        'dashboard.returningCustomers': 'Geri dönen müşteriler',
        'dashboard.visitorTraffic': 'Ziyaretçi Trafiği',
        'dashboard.demographics': 'Demografik Bilgiler',
        
        'dashboard.ageGroups': 'Yaş Grupları',
        'dashboard.liveStoreOverview': 'Canlı Mağaza Görünümü',
        'dashboard.topZones': 'En Çok Ziyaret Edilen Bölgeler',
        'dashboard.smartAlerts': 'Akıllı Uyarılar ve Öneriler',
        'dashboard.queueBuilding': 'Kuyruk Oluşuyor',
        'dashboard.highDemand': 'Yüksek Talep',
        'dashboard.peakEfficiency': 'Maksimum Verimlilik',
        'dashboard.queueLength': 'Kuyruk Uzunluğu',
        'dashboard.peopleWaiting': 'Kişi Bekliyor',
        'dashboard.staffCount': 'Personel Sayısı',
        'dashboard.activeStaff': 'Aktif Personel',
        'dashboard.heatmapIntensity': 'Isı Haritası Yoğunluğu',
        'dashboard.storeOccupancy': 'Mağaza Doluluk Oranı',
        'dashboard.recentActivity': 'Son Aktiviteler',
        'dashboard.customersEntered': 'Giren Müşteri',
        'dashboard.customersExited': 'Çıkan Müşteri',
        'dashboard.customersInside': 'İçerdeki Müşteri',
        'dashboard.dailyCustomerFlowTrend': 'Günlük Müşteri Akışı Trendi',
        'dashboard.dailyAverageVisitDurationTrend': 'Günlük Ortalama Ziyaret Süresi Trendi',
        'dashboard.dailyStoreOccupancyTrend': 'Günlük Mağaza Doluluk Trendi',
        'dashboard.queueLengthVsStaffRelationship': 'Kuyruk Uzunluğu vs Personel İlişkisi',
        'dashboard.enteringCustomers': 'Giren Müşteri',
        'dashboard.exitingCustomers': 'Çıkan Müşteri',
        'dashboard.averageVisitDuration': 'Ort. Ziyaret Süresi (dk)',
        'dashboard.occupancyRate': 'Doluluk Oranı (%)',

        // Analytics (for components using analytics.* keys)
        'analytics.title': 'Müşteri Sayımı',
        'analytics.subtitle': 'Mağaza içi müşteri sayımı ve giriş-çıkış analizi',
        'analytics.totalCustomers': 'İçerdeki Müşteri Sayısı',
        'analytics.newCustomers': 'Giren Müşteri Sayısı',
        'analytics.returningCustomers': 'Çıkan Müşteri Sayısı',
        'analytics.avgVisitDuration': 'Ort. Ziyaret Süresi',
        'analytics.ageDistribution': 'Yaş Dağılımı',
        'analytics.genderDistribution': 'Cinsiyet Dağılımı',
        'analytics.topZones': 'En Çok Ziyaret Edilen Bölgeler',
        'analytics.recentActivity': 'Son Aktiviteler',

        // Staff Management
        'staffManagement.title': 'Personel Yönetimi',
        'staffManagement.subtitle': 'Gerçek zamanlı personel aktivite izleme ve optimizasyon',
        'staffManagement.overallActivity': 'Genel Aktivite',
        'staffManagement.activeStaff': 'Aktif Personel',
        'staffManagement.avgTaskTime': 'Ort. Görev Süresi',
        'staffManagement.efficiencyScore': 'Verimlilik Skoru',
        'staffManagement.currentShiftAverage': 'Mevcut vardiya ortalaması',
        'staffManagement.currentlyOnDuty': 'Şu anda görevde',
        'staffManagement.fasterThanTarget': 'Hedeften daha hızlı',
        'staffManagement.teamPerformance': 'Takım performansı',
        'staffManagement.realTimeActivity': 'Gerçek Zamanlı Personel Aktivitesi',
        'staffManagement.currentStaffStatus': 'Mevcut Personel Durumu',
        'staffManagement.taskPerformanceAnalysis': 'Görev Performans Analizi',
        'staffManagement.zoneCoverageStaffing': 'Bölge Kapsamı ve Personel Dağılımı',
        'staffManagement.aiRecommendations': 'AI Önerileri',

        // Heatmaps
        'heatmaps.title': 'Mağaza Isı Haritaları',
        'heatmaps.subtitle': 'Müşteri hareket ve davranış desenlerinin görsel analizi',
        'heatmaps.visitorTraffic': 'Ziyaretçi Trafiği',
        'heatmaps.dwellTime': 'Bekleme Süresi',
        'heatmaps.queues': 'Kuyruklar',
        'heatmaps.traffic': 'Trafik',
        'heatmaps.duration': 'Süre',
        'heatmaps.queue': 'Kuyruk',
        'heatmaps.storeLayoutHeatmap': 'Mağaza Düzeni Isı Haritası',
        'heatmaps.heatIntensityScale': 'Isı Yoğunluğu Ölçeği',
        'heatmaps.liveUpdates': 'Canlı Güncellemeler',
        'heatmaps.aiPoweredInsights': 'AI Destekli İçgörüler',

        // Shelf Optimization
        'shelfOptimization.title': 'Rayon Optimizasyonu',
        'shelfOptimization.subtitle': 'Optimal ürün yerleşimi ve envanter yönetimi için AI destekli içgörüler',
        'shelfOptimization.activeShelves': 'Aktif Rayonlar',
        'shelfOptimization.avgEngagement': 'Ort. Etkileşim',
        'shelfOptimization.conversionRate': 'Dönüşüm Oranı',
        'shelfOptimization.stockAlerts': 'Stok Uyarıları',
        'shelfOptimization.currentlyMonitored': 'Şu anda izleniyor',
        'shelfOptimization.customerInteraction': 'Müşteri etkileşimi',
        'shelfOptimization.viewToPurchase': 'Görüntülemeden satın almaya',
        'shelfOptimization.requireAttention': 'Dikkat gerektiriyor',
        'shelfOptimization.shelfPerformanceAnalysis': 'Rayon Performans Analizi',
        'shelfOptimization.hourlyInteractionPatterns': 'Saatlik Etkileşim Desenleri',
        'shelfOptimization.placementOptimizationScore': 'Yerleşim Optimizasyon Skoru',
        'shelfOptimization.aiOptimizationRecommendations': 'AI Optimizasyon Önerileri',
        'shelfOptimization.shelfEngagementHeatmap': 'Rayon Etkileşim Isı Haritası',

        // Reports
        'reports.title': 'Raporlar',
        'reports.subtitle': 'Analitik raporları oluşturun, yönetin ve indirin',
        'reports.totalReports': 'Toplam Rapor',
        'reports.thisWeek': 'Bu Hafta',
        'reports.downloads': 'İndirmeler',
        'reports.inProcessing': 'İşlemde',
        'reports.quickReportTemplates': 'Hızlı Rapor Şablonları',
        'reports.generatedReports': 'Oluşturulan Raporlar',
        'reports.newReport': 'Yeni Rapor',
        'reports.searchReports': 'Rapor ara...',
        'reports.allTypes': 'Tüm Türler',
        'reports.customer': 'Müşteri',
        'reports.staff': 'Personel',
        'reports.heatmap': 'Isı Haritası',
        'reports.inventory': 'Envanter',
        'reports.sales': 'Satış',
        'reports.analytics': 'Analitik',
        'reports.advanced': 'Gelişmiş',
        'reports.addImage': 'Görsel Ekle',
        'reports.uploadImage': 'Görsel Yükle',
        'reports.imageGallery': 'Görsel Galerisi',

        // Settings
        'settings.title': 'Ayarlar',
        'settings.subtitle': 'Vislivis deneyiminizi yapılandırın',
        'settings.profile': 'Profil',
        'settings.notifications': 'Bildirimler',
        'settings.security': 'Güvenlik',
        'settings.storeManagement': 'Mağaza Yönetimi',
        'settings.cameraSettings': 'Kamera Ayarları',
        'settings.dataManagement': 'Veri Yönetimi',
        'settings.appearance': 'Görünüm',
        'settings.saveChanges': 'Değişiklikleri Kaydet',
        'settings.cancel': 'İptal',

        // Common
        'common.today': 'Bugün',
        'common.yesterday': 'Dün',
        'common.thisWeek': 'Bu Hafta',
        'common.thisMonth': 'Bu Ay',
        'common.custom': 'Özel',
        'common.filters': 'Filtreler',
        'common.advancedFilters': 'Gelişmiş Filtreler',
        'common.search': 'Ara',
        'common.export': 'Dışa Aktar',
        'common.download': 'İndir',
        'common.view': 'Görüntüle',
        'common.edit': 'Düzenle',
        'common.delete': 'Sil',
        'common.save': 'Kaydet',
        'common.cancel': 'İptal',
        'common.loading': 'Yükleniyor...',
        'common.noData': 'Veri bulunamadı',
        'common.error': 'Hata',
        'common.success': 'Başarılı',
        'common.warning': 'Uyarı',
        'common.info': 'Bilgi',
        'common.live': 'Canlı',
        'common.offline': 'Çevrimdışı',
        'common.online': 'Çevrimiçi',
        'common.active': 'Aktif',
        'common.inactive': 'Pasif',
        'common.high': 'Yüksek',
        'common.medium': 'Orta',
        'common.low': 'Düşük',
        'common.critical': 'Kritik',
        'common.normal': 'Normal',
        'common.good': 'İyi',

        // Chart Data
        'chart.visitors': 'Ziyaretçiler',
        'chart.yesterday': 'Dün',
        'chart.male': 'Erkek',
        'chart.female': 'Kadın',
        'chart.unknown': 'Bilinmeyen',
        'chart.electronics': 'Elektronik',
        'chart.fashion': 'Moda',
        'chart.beauty': 'Güzellik',
        'chart.grocery': 'Market',
        'chart.home': 'Ev & Bahçe',
        'chart.sports': 'Spor',
        'chart.entrance': 'Giriş',
        'chart.checkout': 'Kasa',
        'chart.mainEntrance': 'Ana Giriş',
        'chart.fashionApparel': 'Moda & Giyim',
        'chart.beautyPersonalCare': 'Güzellik & Kişisel Bakım',
        'chart.groceryFood': 'Market & Gıda',
        'chart.homeGarden': 'Ev & Bahçe',
        'chart.checkoutArea': 'Kasa Alanı',
        'chart.happy': 'Mutlu',
        'chart.neutral': 'Nötr',
        'chart.stressed': 'Stresli',
        'chart.vipCustomers': 'VIP Müşteriler',
        'chart.regularCustomers': 'Düzenli Müşteriler',
        'chart.occasionalVisitors': 'Ara Sıra Gelenler',
        'chart.firstTimeVisitors': 'İlk Kez Gelenler',
        'chart.newVisitors': 'Yeni Ziyaretçiler',
        'chart.returningVisitors': 'Geri Dönen Ziyaretçiler',
        'chart.total': 'Toplam',
        'chart.new': 'Yeni',
        'chart.returning': 'Geri Dönen',
        'chart.browse': 'Gezinme',
        'chart.pickItems': 'Ürün Seçimi',
        'chart.queue': 'Kuyruk',
        'chart.purchase': 'Satın Alma',
        'chart.exit': 'Çıkış',
        'chart.dropoff': 'kayıp',
        'chart.of': 'of',

        // Staff Management
        'staff.title': 'Personel Yönetimi',
        'staff.subtitle': 'Gerçek zamanlı personel aktivite izleme ve optimizasyon',
        'staff.totalStaff': 'Toplam Personel',
        'staff.activeStaff': 'Aktif Personel',
        'staff.avgEfficiency': 'Ortalama Verimlilik',
        'staff.efficientHours': 'Verimli Saatler',
        'staff.floorSupervisor': 'Kat Sorumlusu',
        'staff.salesAssociate': 'Satış Danışmanı',
        'staff.cashier': 'Kasiyer',
        'staff.stockAssociate': 'Stok Sorumlusu',
        'staff.customerService': 'Müşteri Hizmetleri',
        'staff.break': 'Mola',
        'staff.tasksToday': 'bugün görev',
        'staff.efficiency': 'verimlilik',
        'staff.customerServiceTask': 'Müşteri Hizmetleri',
        'staff.shelfRestocking': 'Raf Yenileme',
        'staff.checkoutSupport': 'Kasa Desteği',
        'staff.inventoryCheck': 'Envanter Kontrolü',
        'staff.areaCleaning': 'Alan Temizliği',
        'staff.priceUpdates': 'Fiyat Güncellemeleri',
        'staff.highTraffic': 'Yüksek Trafik',
        'staff.mediumTraffic': 'Orta Trafik',
        'staff.lowTraffic': 'Düşük Trafik',
        'staff.highImpact': 'Yüksek Etki',
        'staff.mediumImpact': 'Orta Etki',
        'staff.lowImpact': 'Düşük Etki',

        // Zones
        'zone.electronics': 'Elektronik',
        'zone.fashion': 'Moda',
        'zone.beauty': 'Güzellik',
        'zone.grocery': 'Market',
        'zone.homeGarden': 'Ev & Bahçe',
        'zone.checkout': 'Kasa',
        'zone.entrance': 'Giriş',
        'zone.storage': 'Depo',

        // Time periods
        'time.minutes': 'dakika',
        'time.hours': 'saat',
        'time.days': 'gün',
        'time.weeks': 'hafta',
        'time.months': 'ay',
        'time.ago': 'önce',
        'time.waitTime': 'bekleme süresi',

        // Status
        'status.online': 'Çevrimiçi',
        'status.offline': 'Çevrimdışı',
        'status.maintenance': 'Bakım',
        'status.ready': 'Hazır',
        'status.processing': 'İşleniyor',
        'status.error': 'Hata',

        // Admin / Üyelik Yönetimi
        'admin.title': 'Üyelik Yönetimi',
        'admin.subtitle': 'Tüm kullanıcıları görüntüle ve yönet',
        'admin.newUser': 'Yeni Kullanıcı',
        'admin.searchUsers': 'Kullanıcı ara...',
        'admin.user': 'Kullanıcı',
        'admin.role': 'Rol',
        'admin.setup': 'Kurulum',
        'admin.actions': 'İşlemler',
        'admin.goToPanel': 'Panele Git',
        'admin.usersCount': 'kullanıcı',
        'admin.editUser': 'Kullanıcı Düzenle',
        'admin.cameras': 'kamera',
        'admin.sessionExpired': 'Oturum süresi dolmuş. Lütfen tekrar giriş yapın.',
        'admin.leaveEmptyNoChange': 'boş bırak = değişmez',
        'admin.deleteConfirm': 'kullanıcısını silmek istediğinize emin misiniz?',
        'admin.error': 'Hata oluştu',
        'admin.connectionError': 'Bağlantı hatası',
        'admin.brandManager': 'Marka Yöneticisi',
        'admin.managedStores': 'Yönetilen Mağazalar',
        'storeSwitcher.all': 'Tüm Mağazalar (Konsolide)',

        // Settings / Ayarlar (ek alanlar)
        'settings.profileTab': 'Profil',
        'settings.camerasTab': 'Kamera Ayarları',
        'settings.reportingTab': 'Rapor Gönderimi',
        'settings.profileInfo': 'Profil Bilgileri',
        'settings.username': 'Kullanıcı Adı',
        'settings.usernameReadonly': 'Kullanıcı adı değiştirilemez',
        'settings.fullName': 'Ad Soyad',
        'settings.fullNamePlaceholder': 'Adınız Soyadınız',
        'settings.email': 'E-posta',
        'settings.emailPlaceholder': 'ornek@email.com',
        'settings.profileUpdated': 'Profil güncellendi.',
        'settings.updateFailed': 'Güncelleme başarısız.',
        'settings.serverError': 'Sunucuya bağlanılamadı.',
        'settings.saveProfile': 'Profili Kaydet',
        'settings.changePassword': 'Şifre Değiştir',
        'settings.currentPassword': 'Mevcut Şifre',
        'settings.newPassword': 'Yeni Şifre',
        'settings.newPasswordConfirm': 'Yeni Şifre (Tekrar)',
        'settings.updatePassword': 'Şifreyi Güncelle',
        'settings.passwordsMismatch': 'Yeni şifreler eşleşmiyor.',
        'settings.passwordMinLength': 'Yeni şifre en az 6 karakter olmalıdır.',
        'settings.passwordUpdateFailed': 'Şifre değiştirilemedi.',
        'settings.passwordError': 'Sunucuya bağlanırken bir hata oluştu.',
        'settings.cameraFlows': 'Kamera Akışları ve RTSP Bilgileri',
        'settings.setup': 'Kurulum',
        'settings.cameraSetupDesc': 'Kurulum scripti (data_sender_setup.py) ile gönderilen kamera bilgileri burada listelenir.',
        'settings.cameraName': 'Kamera Adı',
        'settings.type': 'Türü',
        'settings.rtspAddress': 'RTSP Adresi',
        'settings.action': 'İşlem',
        'settings.view': 'Görüntüle',
        'settings.noCameras': 'Henüz kamera eklenmemiş. Kurulum scripti ile gönderin.',
        'settings.noImage': 'Görüntü yok',
        'settings.rtspLabel': 'RTSP Adresi',
        'settings.reportRecipients': 'Rapor Gönderim Listesi',
        'settings.reportRecipientsDesc': 'Oluşturulan otomatik raporların gönderileceği e-posta adreslerini buradan yönetebilirsiniz.',
        'settings.addEmailPlaceholder': 'yeni.email@adres.com',
        'settings.add': 'Ekle',
        'settings.currentRecipients': 'Mevcut Alıcılar',
        'settings.noRecipients': 'Henüz alıcı eklenmemiş.',
        'settings.subtitleFull': 'VISLIVIS sistem ayarlarını yönetin',
        'settings.deleteFailed': 'Silme işlemi başarısız oldu.',

        // Nav (ek)
        'nav.queueAnalysis': 'Kuyruk Analizi',
        'nav.reportAnalytics': 'Rapor Analizi',
        'nav.chat': 'Sohbet (AI)',
        'nav.userManagement': 'Üyelik Yönetimi',
        'nav.activityLogs': 'Aktivite Logları',
        'nav.healthOverview': 'Sistem Sağlık Durumu',
        'healthOverview.title': 'Mağaza AI Sistem Sağlık Durumu',
        'healthOverview.user': 'Kullanıcı / Mağaza',
        'healthOverview.status': 'Durum',
        'healthOverview.lastPing': 'Son sinyal',
        'healthOverview.active': 'Aktif',
        'healthOverview.inactive': 'Kapalı',
        'healthOverview.loading': 'Yükleniyor...',
        'healthOverview.empty': 'Kullanıcı bulunamadı.',
        'healthOverview.refresh': 'Yenile',
        'healthOverview.total': 'Toplam',
        'healthOverview.activeCount': 'Aktif',
        'healthOverview.inactiveCount': 'Kapalı',
        'healthOverview.searchPlaceholder': 'İsim veya e-posta ara...',
        'healthOverview.filterAll': 'Tümü',
        'healthOverview.filterActiveOnly': 'Sadece aktif',
        'healthOverview.filterInactiveOnly': 'Sadece kapalı',
        'healthOverview.autoRefresh': 'Otomatik yenile',
        'healthOverview.role': 'Rol',
        'healthOverview.ago': 'önce',
        'healthOverview.minutes': 'dk',
        'healthOverview.hours': 'saat',
        'healthOverview.days': 'gün',
        'healthOverview.never': 'Hiç sinyal yok',
        'nav.tickets': 'Destek',
        'nav.ticketManagement': 'Ticket Yönetimi',
        'ticket.title': 'Destek Talepleri',
        'ticket.newTicket': 'Yeni Talep Aç',
        'ticket.subject': 'Konu',
        'ticket.category': 'Kategori',
        'ticket.priority': 'Öncelik',
        'ticket.message': 'Mesaj',
        'ticket.submit': 'Gönder',
        'ticket.myTickets': 'Taleplerim',
        'ticket.empty': 'Henüz talep yok.',
        'ticket.openTicket': 'Talep Aç',
        'ticket.back': 'Geri',
        'ticket.reply': 'Cevap Yaz',
        'ticket.sendReply': 'Gönder',
        'ticket.close': 'Kapat',
        'ticket.status': 'Durum',
        'ticket.createdAt': 'Oluşturulma',
        'ticket.category.teknik': 'Teknik',
        'ticket.category.fatura': 'Fatura',
        'ticket.category.genel': 'Genel Destek',
        'ticket.category.diger': 'Diğer',
        'ticket.priority.acil': 'Acil',
        'ticket.priority.yuksek': 'Yüksek',
        'ticket.priority.normal': 'Normal',
        'ticket.priority.dusuk': 'Düşük',
        'ticket.status.open': 'Açık',
        'ticket.status.answered': 'Cevaplandı',
        'ticket.status.closed': 'Kapalı',
        'ticket.admin.title': 'Ticket Yönetimi',
        'ticket.admin.search': 'Ara (konu, mesaj, kullanıcı)',
        'ticket.admin.filterStatus': 'Durum',
        'ticket.admin.filterPriority': 'Öncelik',
        'ticket.admin.filterCategory': 'Kategori',
        'ticket.admin.unreadOnly': 'Sadece okunmamış',
        'ticket.admin.user': 'Kullanıcı',
        'ticket.admin.replyPlaceholder': 'Cevabınızı yazın...',
        'ticket.admin.closeTicket': 'Ticket\'ı Kapat',
        'ticket.admin.ip': 'IP',
        'ticket.admin.userAgent': 'Tarayıcı',
        'ticket.admin.dateFrom': 'Tarih (başlangıç)',
        'ticket.admin.dateTo': 'Tarih (bitiş)',
        'ticket.adminNoCreate': 'Destek talebi sadece kullanıcı hesaplarından açılabilir. Yönetim için Ticket Yönetimi sayfasını kullanın.',
        'ticket.closedBy': 'Kapandı',
        'ticket.closedByAdmin': 'Admin tarafından kapatıldı',
        'ticket.closedByUser': 'Kullanıcı tarafından kapatıldı',
        'ticket.closedByRole': '{{role}} tarafından kapatıldı',
        'ticket.allRequests': 'Tüm Talepler',
        'ticket.admin.filterUser': 'Kullanıcı',
        'ticket.admin.searchButton': 'Ara',
        'ticket.admin.clearFilters': 'Filtre temizle',
        'chat.loadingHistory': 'Geçmiş yükleniyor...',
        'chat.placeholder': 'Mağaza verileriniz hakkında soru sorun. Örn: Bugün satışlar nasıl? Kasa yoğunluğu var mı?',
        'chat.inputPlaceholder': 'Mesajınızı yazın...',
        'chat.send': 'Gönder',
        'chat.sending': 'Gönderiliyor...',
        'chat.newChat': 'Yeni sohbet',
        'chat.conversations': 'Geçmiş sohbetler',
        'chat.deleteChat': 'Sohbeti sil',
        'chat.clearChat': 'Sohbeti temizle',
        'role.admin': 'Yönetici',
        'role.storeManager': 'Mağaza Yöneticisi',
        'role.brandManager': 'Marka Yöneticisi',
        'role.user': 'Kullanıcı',

        // Queue Analysis
        'queue.title': 'Günlük Kuyruk Analizi',
        'queue.subtitle': 'Belirli bir günün saatlik kuyruk performansını inceleyin.',
        'queue.allCashiers': 'Tüm Kasalar',
        'queue.totalCustomers': 'Toplam Müşteri',
        'queue.avgWait': 'Ortalama Bekleme',
        'queue.maxWait': 'Maksimum Bekleme',
        'queue.hourlyDetails': 'Saatlik Performans Detayları (10:00 - 22:00)',
        'queue.cancel': 'İptal',
        'queue.save': 'Kaydet',
        'queue.saving': 'Kaydediliyor...',
        'queue.singleCashierEditDisabled': 'Tekil kasa verileri düzenlenemez. Düzenleme yapmak için lütfen "Tüm Kasalar" filtresini seçin.',
        'queue.timeRange': 'Saat Aralığı',
        'queue.totalCustomersCol': 'Toplam Müşteri',
        'queue.avgWaitSec': 'Ort. Bekleme (sn)',
        'queue.minWait': 'Min. Bekleme',
        'queue.maxWaitCol': 'Maks. Bekleme',
        'queue.adminOnlyEdit': 'Bu alanı sadece adminler düzenleyebilir.',
        'queue.singleCashierNoEdit': 'Tekil kasa verisi düzenlenemez.',
        'queue.noDataThisSlot': 'Bu saat diliminde düzenlenecek veri yok.',
        'queue.hourlyChart': 'Saatlik Müşteri & Bekleme Süresi (10:00 - 22:00)',
        'queue.waitDistribution': 'Bekleme Süresi Dağılımı',
        'queue.noData': 'Veri yok',
        'queue.cashierPerformance': 'Kasa Performans Analizi (Tüm Kasalar)',
        'queue.customerCount': 'Müşteri Sayısı',
        'queue.loading': 'Veriler Yükleniyor...',

        // Heatmaps / Yoğunluk
        'heatmap.title': 'Yoğunluk Analizi',
        'heatmap.subtitle': 'Belirli bir günün saatlik bölge yoğunluğunu ve bekleme sürelerini inceleyin.',
        'heatmap.allZones': 'Tüm Bölgeler',
        'heatmap.zone': 'Bölge',
        'heatmap.visitorChange': 'Ziyaretçi Değişimi',
        'heatmap.avgDwell': 'Ort. Bekleme Süresi',
        'heatmap.busiestZone': 'En Yoğun Bölge',
        'heatmap.hourlyDetails': 'Saatlik Performans Detayları (10:00 - 22:00)',
        'heatmap.cancel': 'İptal',
        'heatmap.save': 'Kaydet',
        'heatmap.saving': 'Kaydediliyor...',
        'heatmap.singleZoneEditDisabled': 'Tekil bölge verileri düzenlenemez. Düzenleme yapmak için lütfen "Tüm Bölgeler" filtresini seçin.',
        'heatmap.timeRange': 'Saat Aralığı',
        'heatmap.avgDwellSec': 'Ort. Bekleme (sn)',
        'heatmap.visitorChangeCol': 'Ziyaretçi Değişimi',
        'heatmap.dwellChange': 'Bekleme Süresi Değişimi',
        'heatmap.hourlyVisitorDwell': 'Saatlik Ziyaretçi & Bekleme Süresi (10:00 - 22:00)',
        'heatmap.zonePerformance': 'Bölge Performans Analizi',
        'heatmap.visitorCount': 'Ziyaretçi Sayısı',
        'heatmap.dwellTimeSec': 'Bekleme (sn)',
        'heatmap.avgDwellChart': 'Ort. Bekleme Süresi',
        'heatmap.totalVisitor': 'Toplam Ziyaretçi',
        'heatmap.avgDwellShort': 'Ort. Bekleme',
        'heatmap.loading': 'Veriler Yükleniyor...',

        // Report Analytics
        'report.title': 'Yapay Zeka Rapor Analizi (Beta)',
        'report.subtitle': 'Yapay Zeka ile verilerinizi analiz edin ve metinsel raporlar oluşturun',
        'report.accessDenied': 'Bu sayfaya erişim yetkiniz bulunmamaktadır. Sadece yönetici kullanıcılar rapor analizi sayfasına erişebilir.',
        'report.newAnalysis': 'Yeni Analiz Oluştur',
        'report.selectType': '1. Analiz Türünü Seçin',
        'report.selectDateRange': '2. Tarih Aralığını Seçin',
        'report.customerAnalysis': 'Müşteri Analizi',
        'report.heatmapAnalysis': 'Isı Haritası Analizi',
        'report.queueAnalysis': 'Kuyruk Analizi',
        'report.createAnalysis': 'Analiz Oluştur',
        'report.creatingAnalysis': 'Analiz Oluşturuluyor... (Bu işlem 1 dakika sürebilir)',
        'report.createdAnalyses': 'Oluşturulan Analizler',
        'report.noAnalyses': 'Henüz bir analiz oluşturulmamış.',
        'report.selectTypeAndDate': 'Lütfen analiz türü ve tarih aralığı seçin.',
        'report.errorCreating': 'Analiz oluşturulurken bir hata oluştu.',
        'report.networkError': 'Ağ bağlantı hatası, sunucu çalışıyor mu?',
        'report.completed': 'Tamamlandı',
        'report.processing': 'İşleniyor',
        'report.failed': 'Başarısız',

        // Login ek
        'login.usernameOrEmail': 'Kullanıcı adı veya e-posta',

        // Mesajlar
        'msg.tokenError': 'Sunucu token döndürmedi.',
        'msg.loginFailed': 'Giriş başarısız',
        'msg.serverError': 'Sunucu bağlantı hatası. Backend çalışıyor mu?',
        'msg.adminAccount': 'Admin hesap: admin / admin',
        'login.errorWrongCredentials': 'Kullanıcı adı veya şifre hatalı. Lütfen tekrar deneyin.',
        'login.errorHint': 'Demo hesap: admin / admin',

        // Staff (ek)
        'staff.statusActive': 'Aktif',
        'staff.statusBreak': 'Mola',
        'staff.statusInactive': 'Pasif',
        'staff.view': 'Görüntüle',
        'staff.none': 'Yok',
        'staff.recordsFrom': 'kayıttan',
        'staff.showingRange': 'arası gösteriliyor',
        'staff.paginationShowing': 'Showing',
        'staff.paginationOf': 'of',
        'staff.records': 'kayıt',
        'staff.pageOf': 'Sayfa',
        'staff.positionDistribution': 'Pozisyona Göre Personel Dağılımı',
        'staff.hours': 'saat',
        'color.red': 'Kırmızı',
        'color.blue': 'Mavi',
        'color.green': 'Yeşil',
        'color.yellow': 'Sarı',
        'color.purple': 'Mor',
        'color.orange': 'Turuncu',
        'color.pink': 'Pembe',
        'color.cyan': 'Cyan',

        // Hava
        'weather.clear': 'Açık',
        'weather.cloudy': 'Bulutlu',
        'weather.rainy': 'Yağmurlu',
        'weather.unknown': 'Bilinmiyor',

        // Health
        'health.checking': 'Sistem durumu kontrol ediliyor...',
        'health.systemActive': 'Sistem Aktif',
        'health.systemError': 'Sistem Hatası',
        'health.connectionFailed': 'Sistem bağlantısı kurulamadı. Sunucu erişilebilir değil.',
        'health.title': 'Sistem Sağlık Durumu',
        'health.status': 'Sistem Durumu',

        // Mağaza AI servis durumu
        'serviceHeartbeat.title': 'Mağaza AI Servis Durumu',
        'serviceHeartbeat.label': 'Mağaza AI',
        'serviceHeartbeat.checking': 'Kontrol ediliyor...',
        'serviceHeartbeat.alive': 'Mağaza servisi ayakta. Son sinyal alındı.',
        'serviceHeartbeat.dead': '5 dakikadır veri gelmiyor. Sistem çökmüş veya bağlantı yok.',
        'serviceHeartbeat.noData': 'Henüz heartbeat gelmedi. Mağaza scripti çalışıyor mu?',
        'serviceHeartbeat.error': 'Durum alınamadı.',

        // Hava uyarısı
        'weatherAlert.title': 'Hava Durumu Uyarısı',
        'weatherAlert.message': 'Önümüzdeki 15 gün içinde yağış bekleniyor. Operasyonel planlamanızı gözden geçirin.'
      },
      en: {

        'dashboard.weeklyOverview': 'Weekly overview of your store performance',
        'dashboard.ageDistribution': 'Age Distribution',
        'dashboard.genderDistribution': 'Gender Distribution',
        'dashboard.avgQueueTime': 'Avg. Queue Time',
        'dashboard.busiestCashier': 'Busiest Cashier',
        'dashboard.weeklyCustomers': 'Weekly Customers',
        'dashboard.dailyGenderDistribution': 'Daily Gender Distribution',
        'dashboard.dailyAgeDistribution': 'Daily Age Analysis',
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.customerAnalytics': 'Customer Analytics',
        'nav.staffManagement': 'Staff Management',
        'nav.heatmaps': 'Heatmaps',
        'nav.shelfOptimization': 'Shelf Optimization',
        'nav.reports': 'Reports',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',

        // Login
        'login.title': 'VISLIVIS',
        'login.subtitle': 'AI-Powered Retail Analytics Platform',
        'login.email': 'Email Address',
        'login.password': 'Password',
        'login.rememberMe': 'Remember me',
        'login.forgotPassword': 'Forgot password?',
        'login.signIn': 'Sign In to Dashboard',
        'login.demoAccounts': 'Demo Accounts:',
        'login.poweredBy': 'Powered by Advanced AI & Computer Vision Technology',
        'login.invalidCredentials': 'Invalid username or password!',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Overview of your store performance',
        'dashboard.totalCustomers': 'Total Customers',
        'dashboard.totalRevenue': 'Total Revenue',
        'dashboard.totalOrders': 'Total Orders',
        'dashboard.conversionRate': 'Conversion Rate',
        'dashboard.totalVisitors': 'Total Visitors',
        'dashboard.avgVisitDuration': 'Avg. Visit Duration',
        'dashboard.potentialLostSales': 'Potential Lost Sales',
        'dashboard.staffActivityRate': 'Staff Activity Rate',
        'dashboard.peakHour': 'Peak Hour',
        'dashboard.loyaltyIndex': 'Loyalty Index',
        'dashboard.today': 'Today',
        'dashboard.minutes': 'Minutes',
        'dashboard.dueToQueues': 'Due to queues',
        'dashboard.currentShift': 'Current shift',
        'dashboard.visitors': 'visitors',
        'dashboard.returningCustomers': 'Returning customers',
        'dashboard.visitorTraffic': 'Visitor Traffic',
        'dashboard.demographics': 'Demographics',
        
        'dashboard.ageGroups': 'Age Groups',
        'dashboard.liveStoreOverview': 'Live Store Overview',
        'dashboard.topZones': 'Top Zones',
        'dashboard.smartAlerts': 'Smart Alerts & Recommendations',
        'dashboard.queueBuilding': 'Queue Building',
        'dashboard.highDemand': 'High Demand',
        'dashboard.peakEfficiency': 'Peak Efficiency',
        'dashboard.queueLength': 'Queue Length',
        'dashboard.peopleWaiting': 'People Waiting',
        'dashboard.staffCount': 'Staff Count',
        'dashboard.activeStaff': 'Active Staff',
        'dashboard.heatmapIntensity': 'Heatmap Intensity',
        'dashboard.storeOccupancy': 'Store Occupancy',
        'dashboard.recentActivity': 'Recent Activity',
        'dashboard.customersEntered': 'Customers Entered',
        'dashboard.customersExited': 'Customers Exited',
        'dashboard.customersInside': 'Customers Inside',
        'dashboard.dailyCustomerFlowTrend': 'Daily Customer Flow Trend',
        'dashboard.dailyAverageVisitDurationTrend': 'Daily Average Visit Duration Trend',
        'dashboard.dailyStoreOccupancyTrend': 'Daily Store Occupancy Trend',
        'dashboard.queueLengthVsStaffRelationship': 'Queue Length vs Staff Relationship',
        'dashboard.enteringCustomers': 'Entering Customers',
        'dashboard.exitingCustomers': 'Exiting Customers',
        'dashboard.averageVisitDuration': 'Avg. Visit Duration (min)',
        'dashboard.occupancyRate': 'Occupancy Rate (%)',

        // Analytics (for components using analytics.* keys)
        'analytics.title': 'Customer Count',
        'analytics.subtitle': 'In-store customer count and entrance-exit analysis',
        'analytics.totalCustomers': 'Total Customers Inside',
        'analytics.newCustomers': 'New Customers',
        'analytics.returningCustomers': 'Returning Customers',
        'analytics.avgVisitDuration': 'Avg. Visit Duration',
        'analytics.ageDistribution': 'Age Distribution',
        'analytics.genderDistribution': 'Gender Distribution',
        'analytics.topZones': 'Top Zones',
        'analytics.recentActivity': 'Recent Activity',

        // Staff Management
        'staffManagement.title': 'Staff Management',
        'staffManagement.subtitle': 'Real-time staff activity monitoring and optimization',
        'staffManagement.overallActivity': 'Overall Activity',
        'staffManagement.activeStaff': 'Active Staff',
        'staffManagement.avgTaskTime': 'Avg Task Time',
        'staffManagement.efficiencyScore': 'Efficiency Score',
        'staffManagement.currentShiftAverage': 'Current shift average',
        'staffManagement.currentlyOnDuty': 'Currently on duty',
        'staffManagement.fasterThanTarget': 'Faster than target',
        'staffManagement.teamPerformance': 'Team performance',
        'staffManagement.realTimeActivity': 'Real-time Staff Activity',
        'staffManagement.currentStaffStatus': 'Current Staff Status',
        'staffManagement.taskPerformanceAnalysis': 'Task Performance Analysis',
        'staffManagement.zoneCoverageStaffing': 'Zone Coverage & Staffing',
        'staffManagement.aiRecommendations': 'AI Recommendations',

        // Heatmaps
        'heatmaps.title': 'Store Heatmaps',
        'heatmaps.subtitle': 'Visual analytics of customer movement and behavior patterns',
        'heatmaps.visitorTraffic': 'Visitor Traffic',
        'heatmaps.dwellTime': 'Dwell Time',
        'heatmaps.queues': 'Queues',
        'heatmaps.traffic': 'Traffic',
        'heatmaps.duration': 'Duration',
        'heatmaps.queue': 'Queue',
        'heatmaps.storeLayoutHeatmap': 'Store Layout Heatmap',
        'heatmaps.heatIntensityScale': 'Heat Intensity Scale',
        'heatmaps.liveUpdates': 'Live Updates',
        'heatmaps.aiPoweredInsights': 'AI-Powered Insights',

        // Shelf Optimization
        'shelfOptimization.title': 'Shelf Optimization',
        'shelfOptimization.subtitle': 'AI-powered insights for optimal product placement and inventory management',
        'shelfOptimization.activeShelves': 'Active Shelves',
        'shelfOptimization.avgEngagement': 'Avg. Engagement',
        'shelfOptimization.conversionRate': 'Conversion Rate',
        'shelfOptimization.stockAlerts': 'Stock Alerts',
        'shelfOptimization.currentlyMonitored': 'Currently monitored',
        'shelfOptimization.customerInteraction': 'Customer interaction',
        'shelfOptimization.viewToPurchase': 'View to purchase',
        'shelfOptimization.requireAttention': 'Require attention',
        'shelfOptimization.shelfPerformanceAnalysis': 'Shelf Performance Analysis',
        'shelfOptimization.hourlyInteractionPatterns': 'Hourly Interaction Patterns',
        'shelfOptimization.placementOptimizationScore': 'Placement Optimization Score',
        'shelfOptimization.aiOptimizationRecommendations': 'AI Optimization Recommendations',
        'shelfOptimization.shelfEngagementHeatmap': 'Shelf Engagement Heatmap',

        // Reports
        'reports.title': 'Reports',
        'reports.subtitle': 'Generate, manage, and download analytics reports',
        'reports.totalReports': 'Total Reports',
        'reports.thisWeek': 'This Week',
        'reports.downloads': 'Downloads',
        'reports.inProcessing': 'In Processing',
        'reports.quickReportTemplates': 'Quick Report Templates',
        'reports.generatedReports': 'Generated Reports',
        'reports.newReport': 'New Report',
        'reports.searchReports': 'Search reports...',
        'reports.allTypes': 'All Types',
        'reports.customer': 'Customer',
        'reports.staff': 'Staff',
        'reports.heatmap': 'Heatmap',
        'reports.inventory': 'Inventory',
        'reports.sales': 'Sales',
        'reports.analytics': 'Analytics',
        'reports.advanced': 'Advanced',
        'reports.addImage': 'Add Image',
        'reports.uploadImage': 'Upload Image',
        'reports.imageGallery': 'Image Gallery',

        // Settings
        'settings.title': 'Settings',
        'settings.subtitle': 'Configure your Vislivis experience',
        'settings.profile': 'Profile',
        'settings.notifications': 'Notifications',
        'settings.security': 'Security',
        'settings.storeManagement': 'Store Management',
        'settings.cameraSettings': 'Camera Settings',
        'settings.dataManagement': 'Data Management',
        'settings.appearance': 'Appearance',
        'settings.saveChanges': 'Save Changes',
        'settings.cancel': 'Cancel',

        // Common
        'common.today': 'Today',
        'common.yesterday': 'Yesterday',
        'common.thisWeek': 'This Week',
        'common.thisMonth': 'This Month',
        'common.custom': 'Custom',
        'common.filters': 'Filters',
        'common.advancedFilters': 'Advanced Filters',
        'common.search': 'Search',
        'common.export': 'Export',
        'common.download': 'Download',
        'common.view': 'View',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.loading': 'Loading...',
        'common.noData': 'No data found',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.warning': 'Warning',
        'common.info': 'Info',
        'common.live': 'Live',
        'common.offline': 'Offline',
        'common.online': 'Online',
        'common.active': 'Active',
        'common.inactive': 'Inactive',
        'common.high': 'High',
        'common.medium': 'Medium',
        'common.low': 'Low',
        'common.critical': 'Critical',
        'common.normal': 'Normal',
        'common.good': 'Good',

        // Chart Data
        'chart.visitors': 'Visitors',
        'chart.yesterday': 'Yesterday',
        'chart.male': 'Male',
        'chart.female': 'Female',
        'chart.unknown': 'Unknown',
        'chart.electronics': 'Electronics',
        'chart.fashion': 'Fashion',
        'chart.beauty': 'Beauty',
        'chart.grocery': 'Grocery',
        'chart.home': 'Home & Garden',
        'chart.sports': 'Sports',
        'chart.entrance': 'Entrance',
        'chart.checkout': 'Checkout',
        'chart.mainEntrance': 'Main Entrance',
        'chart.fashionApparel': 'Fashion & Apparel',
        'chart.beautyPersonalCare': 'Beauty & Personal Care',
        'chart.groceryFood': 'Grocery & Food',
        'chart.homeGarden': 'Home & Garden',
        'chart.checkoutArea': 'Checkout Area',
        'chart.happy': 'Happy',
        'chart.neutral': 'Neutral',
        'chart.stressed': 'Stressed',
        'chart.vipCustomers': 'VIP Customers',
        'chart.regularCustomers': 'Regular Customers',
        'chart.occasionalVisitors': 'Occasional Visitors',
        'chart.firstTimeVisitors': 'First-time Visitors',
        'chart.newVisitors': 'New Visitors',
        'chart.returningVisitors': 'Returning Visitors',
        'chart.total': 'Total',
        'chart.new': 'New',
        'chart.returning': 'Returning',
        'chart.browse': 'Browse',
        'chart.pickItems': 'Pick Items',
        'chart.queue': 'Queue',
        'chart.purchase': 'Purchase',
        'chart.exit': 'Exit',
        'chart.dropoff': 'dropoff',
        'chart.of': 'of',

        // Staff Management
        'staff.title': 'Staff Management',
        'staff.subtitle': 'Real-time staff activity monitoring and optimization',
        'staff.totalStaff': 'Total Staff',
        'staff.activeStaff': 'Active Staff',
        'staff.avgEfficiency': 'Average Efficiency',
        'staff.efficientHours': 'Efficient Hours',
        'staff.floorSupervisor': 'Floor Supervisor',
        'staff.salesAssociate': 'Sales Associate',
        'staff.cashier': 'Cashier',
        'staff.stockAssociate': 'Stock Associate',
        'staff.customerService': 'Customer Service',
        'staff.break': 'Break',
        'staff.tasksToday': 'tasks today',
        'staff.efficiency': 'efficiency',
        'staff.customerServiceTask': 'Customer Service',
        'staff.shelfRestocking': 'Shelf Restocking',
        'staff.checkoutSupport': 'Checkout Support',
        'staff.inventoryCheck': 'Inventory Check',
        'staff.areaCleaning': 'Area Cleaning',
        'staff.priceUpdates': 'Price Updates',
        'staff.highTraffic': 'High Traffic',
        'staff.mediumTraffic': 'Medium Traffic',
        'staff.lowTraffic': 'Low Traffic',
        'staff.highImpact': 'High Impact',
        'staff.mediumImpact': 'Medium Impact',
        'staff.lowImpact': 'Low Impact',

        // Zones
        'zone.electronics': 'Electronics',
        'zone.fashion': 'Fashion',
        'zone.beauty': 'Beauty',
        'zone.grocery': 'Grocery',
        'zone.homeGarden': 'Home & Garden',
        'zone.checkout': 'Checkout',
        'zone.entrance': 'Entrance',
        'zone.storage': 'Storage',

        // Time periods
        'time.minutes': 'minutes',
        'time.hours': 'hours',
        'time.days': 'days',
        'time.weeks': 'weeks',
        'time.months': 'months',
        'time.ago': 'ago',
        'time.waitTime': 'wait time',

        // Status
        'status.online': 'Online',
        'status.offline': 'Offline',
        'status.maintenance': 'Maintenance',
        'status.ready': 'Ready',
        'status.processing': 'Processing',
        'status.error': 'Error',

        // Admin / User Management
        'admin.title': 'User Management',
        'admin.subtitle': 'View and manage all users',
        'admin.newUser': 'New User',
        'admin.searchUsers': 'Search users...',
        'admin.user': 'User',
        'admin.role': 'Role',
        'admin.setup': 'Setup',
        'admin.actions': 'Actions',
        'admin.goToPanel': 'Go to Panel',
        'admin.usersCount': 'users',
        'admin.editUser': 'Edit User',
        'admin.cameras': 'cameras',
        'admin.sessionExpired': 'Session expired. Please log in again.',
        'admin.leaveEmptyNoChange': 'leave empty = no change',
        'admin.deleteConfirm': 'Are you sure you want to delete user',
        'admin.error': 'An error occurred',
        'admin.connectionError': 'Connection error',
        'admin.brandManager': 'Brand Manager',
        'admin.managedStores': 'Managed Stores',
        'storeSwitcher.all': 'All Stores (Consolidated)',

        // Settings
        'settings.profileTab': 'Profile',
        'settings.camerasTab': 'Camera Settings',
        'settings.reportingTab': 'Report Sending',
        'settings.profileInfo': 'Profile Information',
        'settings.username': 'Username',
        'settings.usernameReadonly': 'Username cannot be changed',
        'settings.fullName': 'Full Name',
        'settings.fullNamePlaceholder': 'Your full name',
        'settings.email': 'Email',
        'settings.emailPlaceholder': 'example@email.com',
        'settings.profileUpdated': 'Profile updated.',
        'settings.updateFailed': 'Update failed.',
        'settings.serverError': 'Could not connect to server.',
        'settings.saveProfile': 'Save Profile',
        'settings.changePassword': 'Change Password',
        'settings.currentPassword': 'Current Password',
        'settings.newPassword': 'New Password',
        'settings.newPasswordConfirm': 'New Password (Confirm)',
        'settings.updatePassword': 'Update Password',
        'settings.passwordsMismatch': 'New passwords do not match.',
        'settings.passwordMinLength': 'New password must be at least 6 characters.',
        'settings.passwordUpdateFailed': 'Could not change password.',
        'settings.passwordError': 'An error occurred while connecting to server.',
        'settings.cameraFlows': 'Camera Streams and RTSP Information',
        'settings.setup': 'Setup',
        'settings.cameraSetupDesc': 'Camera information sent via the setup script (data_sender_setup.py) is listed here.',
        'settings.cameraName': 'Camera Name',
        'settings.type': 'Type',
        'settings.rtspAddress': 'RTSP Address',
        'settings.action': 'Action',
        'settings.view': 'View',
        'settings.noCameras': 'No cameras added yet. Send via setup script.',
        'settings.noImage': 'No image',
        'settings.rtspLabel': 'RTSP Address',
        'settings.reportRecipients': 'Report Recipients List',
        'settings.reportRecipientsDesc': 'Manage the email addresses where automated reports will be sent.',
        'settings.addEmailPlaceholder': 'new.email@address.com',
        'settings.add': 'Add',
        'settings.currentRecipients': 'Current Recipients',
        'settings.noRecipients': 'No recipients added yet.',
        'settings.subtitleFull': 'Manage VISLIVIS system settings',
        'settings.deleteFailed': 'Delete operation failed.',

        // Nav
        'nav.queueAnalysis': 'Queue Analysis',
        'nav.reportAnalytics': 'Report Analytics',
        'nav.chat': 'Chat (AI)',
        'nav.userManagement': 'User Management',
        'nav.activityLogs': 'Activity Logs',
        'nav.healthOverview': 'System Health',
        'healthOverview.title': 'Store AI System Health Status',
        'healthOverview.user': 'User / Store',
        'healthOverview.status': 'Status',
        'healthOverview.lastPing': 'Last signal',
        'healthOverview.active': 'Active',
        'healthOverview.inactive': 'Inactive',
        'healthOverview.loading': 'Loading...',
        'healthOverview.empty': 'No users found.',
        'healthOverview.refresh': 'Refresh',
        'healthOverview.total': 'Total',
        'healthOverview.activeCount': 'Active',
        'healthOverview.inactiveCount': 'Inactive',
        'healthOverview.searchPlaceholder': 'Search by name or email...',
        'healthOverview.filterAll': 'All',
        'healthOverview.filterActiveOnly': 'Active only',
        'healthOverview.filterInactiveOnly': 'Inactive only',
        'healthOverview.autoRefresh': 'Auto refresh',
        'healthOverview.role': 'Role',
        'healthOverview.ago': 'ago',
        'healthOverview.minutes': 'm',
        'healthOverview.hours': 'h',
        'healthOverview.days': 'd',
        'healthOverview.never': 'No signal',
        'nav.tickets': 'Support',
        'nav.ticketManagement': 'Ticket Management',
        'ticket.title': 'Support Tickets',
        'ticket.newTicket': 'New Ticket',
        'ticket.subject': 'Subject',
        'ticket.category': 'Category',
        'ticket.priority': 'Priority',
        'ticket.message': 'Message',
        'ticket.submit': 'Submit',
        'ticket.myTickets': 'My Tickets',
        'ticket.empty': 'No tickets yet.',
        'ticket.openTicket': 'Open Ticket',
        'ticket.back': 'Back',
        'ticket.reply': 'Reply',
        'ticket.sendReply': 'Send',
        'ticket.close': 'Close',
        'ticket.status': 'Status',
        'ticket.createdAt': 'Created',
        'ticket.category.teknik': 'Technical',
        'ticket.category.fatura': 'Billing',
        'ticket.category.genel': 'General Support',
        'ticket.category.diger': 'Other',
        'ticket.priority.acil': 'Urgent',
        'ticket.priority.yuksek': 'High',
        'ticket.priority.normal': 'Normal',
        'ticket.priority.dusuk': 'Low',
        'ticket.status.open': 'Open',
        'ticket.status.answered': 'Answered',
        'ticket.status.closed': 'Closed',
        'ticket.admin.title': 'Ticket Management',
        'ticket.admin.search': 'Search (subject, message, user)',
        'ticket.admin.filterStatus': 'Status',
        'ticket.admin.filterPriority': 'Priority',
        'ticket.admin.filterCategory': 'Category',
        'ticket.admin.unreadOnly': 'Unread only',
        'ticket.admin.user': 'User',
        'ticket.admin.replyPlaceholder': 'Write your reply...',
        'ticket.admin.closeTicket': 'Close Ticket',
        'ticket.admin.ip': 'IP',
        'ticket.admin.userAgent': 'Browser',
        'ticket.admin.dateFrom': 'Date (from)',
        'ticket.admin.dateTo': 'Date (to)',
        'ticket.adminNoCreate': 'Support tickets can only be opened by user accounts. Use Ticket Management for admin.',
        'ticket.closedBy': 'Closed by',
        'ticket.closedByAdmin': 'Closed by Admin',
        'ticket.closedByUser': 'Closed by User',
        'ticket.closedByRole': 'Closed by {{role}}',
        'ticket.allRequests': 'All Requests',
        'ticket.admin.filterUser': 'User',
        'ticket.admin.searchButton': 'Search',
        'ticket.admin.clearFilters': 'Clear filters',
        'role.admin': 'Admin',
        'chat.loadingHistory': 'Loading history...',
        'chat.placeholder': 'Ask about your store data. E.g. How are sales today? Is there queue congestion?',
        'chat.inputPlaceholder': 'Type your message...',
        'chat.send': 'Send',
        'chat.sending': 'Sending...',
        'chat.newChat': 'New chat',
        'chat.conversations': 'Past chats',
        'chat.deleteChat': 'Delete chat',
        'chat.clearChat': 'Clear chat',
        'role.storeManager': 'Store Manager',
        'role.brandManager': 'Brand Manager',
        'role.user': 'User',

        // Queue Analysis
        'queue.title': 'Daily Queue Analysis',
        'queue.subtitle': 'View hourly queue performance for a specific day.',
        'queue.allCashiers': 'All Cashiers',
        'queue.totalCustomers': 'Total Customers',
        'queue.avgWait': 'Avg. Wait Time',
        'queue.maxWait': 'Max Wait Time',
        'queue.hourlyDetails': 'Hourly Performance Details (10:00 - 22:00)',
        'queue.cancel': 'Cancel',
        'queue.save': 'Save',
        'queue.saving': 'Saving...',
        'queue.singleCashierEditDisabled': 'Single cashier data cannot be edited. Please select "All Cashiers" filter to edit.',
        'queue.timeRange': 'Time Range',
        'queue.totalCustomersCol': 'Total Customers',
        'queue.avgWaitSec': 'Avg. Wait (s)',
        'queue.minWait': 'Min. Wait',
        'queue.maxWaitCol': 'Max. Wait',
        'queue.adminOnlyEdit': 'Only admins can edit this field.',
        'queue.singleCashierNoEdit': 'Single cashier data cannot be edited.',
        'queue.noDataThisSlot': 'No data to edit for this time slot.',
        'queue.hourlyChart': 'Hourly Customers & Wait Time (10:00 - 22:00)',
        'queue.waitDistribution': 'Wait Time Distribution',
        'queue.noData': 'No data',
        'queue.cashierPerformance': 'Cashier Performance Analysis (All Cashiers)',
        'queue.customerCount': 'Customer Count',
        'queue.loading': 'Loading data...',

        // Heatmaps
        'heatmap.title': 'Intensity Analysis',
        'heatmap.subtitle': 'View hourly zone intensity and dwell times for a specific day.',
        'heatmap.allZones': 'All Zones',
        'heatmap.zone': 'Zone',
        'heatmap.visitorChange': 'Visitor Change',
        'heatmap.avgDwell': 'Avg. Dwell Time',
        'heatmap.busiestZone': 'Busiest Zone',
        'heatmap.hourlyDetails': 'Hourly Performance Details (10:00 - 22:00)',
        'heatmap.cancel': 'Cancel',
        'heatmap.save': 'Save',
        'heatmap.saving': 'Saving...',
        'heatmap.singleZoneEditDisabled': 'Single zone data cannot be edited. Please select "All Zones" filter to edit.',
        'heatmap.timeRange': 'Time Range',
        'heatmap.avgDwellSec': 'Avg. Dwell (s)',
        'heatmap.visitorChangeCol': 'Visitor Change',
        'heatmap.dwellChange': 'Dwell Time Change',
        'heatmap.hourlyVisitorDwell': 'Hourly Visitors & Dwell Time (10:00 - 22:00)',
        'heatmap.zonePerformance': 'Zone Performance Analysis',
        'heatmap.visitorCount': 'Visitor Count',
        'heatmap.dwellTimeSec': 'Dwell (s)',
        'heatmap.avgDwellChart': 'Avg. Dwell Time',
        'heatmap.totalVisitor': 'Total Visitors',
        'heatmap.avgDwellShort': 'Avg. Dwell',
        'heatmap.loading': 'Loading data...',

        // Report Analytics
        'report.title': 'AI Report Analytics (Beta)',
        'report.subtitle': 'Analyze your data with AI and create text reports',
        'report.accessDenied': 'You do not have permission to access this page. Only administrator users can access the report analytics page.',
        'report.newAnalysis': 'Create New Analysis',
        'report.selectType': '1. Select Analysis Type',
        'report.selectDateRange': '2. Select Date Range',
        'report.customerAnalysis': 'Customer Analysis',
        'report.heatmapAnalysis': 'Heatmap Analysis',
        'report.queueAnalysis': 'Queue Analysis',
        'report.createAnalysis': 'Create Analysis',
        'report.creatingAnalysis': 'Creating analysis... (This may take 1 minute)',
        'report.createdAnalyses': 'Created Analyses',
        'report.noAnalyses': 'No analyses created yet.',
        'report.selectTypeAndDate': 'Please select analysis type and date range.',
        'report.errorCreating': 'An error occurred while creating analysis.',
        'report.networkError': 'Network connection error. Is the server running?',
        'report.completed': 'Completed',
        'report.processing': 'Processing',
        'report.failed': 'Failed',

        // Login
        'login.usernameOrEmail': 'Username or email',

        // Messages
        'msg.tokenError': 'Server did not return token.',
        'msg.loginFailed': 'Login failed',
        'msg.serverError': 'Server connection error. Is the backend running?',
        'msg.adminAccount': 'Admin account: admin / admin',
        'login.errorWrongCredentials': 'Invalid username or password. Please try again.',
        'login.errorHint': 'Demo account: admin / admin',

        // Staff
        'staff.statusActive': 'Active',
        'staff.statusBreak': 'Break',
        'staff.statusInactive': 'Inactive',
        'staff.view': 'View',
        'staff.none': 'None',
        'staff.recordsFrom': 'records',
        'staff.showingRange': 'showing',
        'staff.paginationShowing': 'Showing',
        'staff.paginationOf': 'of',
        'staff.records': 'records',
        'staff.pageOf': 'Page',
        'staff.positionDistribution': 'Staff Distribution by Position',
        'staff.hours': 'hours',
        'color.red': 'Red',
        'color.blue': 'Blue',
        'color.green': 'Green',
        'color.yellow': 'Yellow',
        'color.purple': 'Purple',
        'color.orange': 'Orange',
        'color.pink': 'Pink',
        'color.cyan': 'Cyan',

        // Weather
        'weather.clear': 'Clear',
        'weather.cloudy': 'Cloudy',
        'weather.rainy': 'Rainy',
        'weather.unknown': 'Unknown',

        // Health
        'health.checking': 'Checking system status...',
        'health.systemActive': 'System Active',
        'health.systemError': 'System Error',
        'health.connectionFailed': 'Could not connect to system. Server is not reachable.',
        'health.title': 'System Health Status',
        'health.status': 'System Status',

        // Service heartbeat
        'serviceHeartbeat.title': 'Store AI Service Status',
        'serviceHeartbeat.label': 'Store AI',
        'serviceHeartbeat.checking': 'Checking...',
        'serviceHeartbeat.alive': 'Store service is online. Last signal received.',
        'serviceHeartbeat.dead': 'No data for 5 minutes. System may be down or disconnected.',
        'serviceHeartbeat.noData': 'No heartbeat yet. Is the store script running?',
        'serviceHeartbeat.error': 'Could not fetch status.',

        // Weather alert
        'weatherAlert.title': 'Weather Alert',
        'weatherAlert.message': 'Rain expected in the next 15 days. Please review your operational planning.'
      }
    };

    const currentTranslations = translations[language as keyof typeof translations] || translations.tr;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};