import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Web versiyonundaki tüm çevirileri içeren tam çeviri objesi
const translations: Record<Language, Record<string, string>> = {
  tr: {
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.view': 'Görüntüle',
    'common.close': 'Kapat',
    'common.noData': 'Veri bulunamadı',
    'common.success': 'Başarılı',
    'common.warning': 'Uyarı',
    'common.info': 'Bilgi',
    'common.today': 'Bugün',
    'common.yesterday': 'Dün',
    'common.thisWeek': 'Bu Hafta',
    'common.thisMonth': 'Bu Ay',
    'common.custom': 'Özel',
    'common.filters': 'Filtreler',
    'common.search': 'Ara',
    'common.export': 'Dışa Aktar',
    'common.download': 'İndir',
    'common.live': 'Canlı',
    'common.offline': 'Çevrimdışı',
    'common.online': 'Çevrimiçi',
    'common.active': 'Aktif',
    'common.inactive': 'Pasif',
    'common.high': 'Yüksek',
    'common.medium': 'Orta',
    'common.low': 'Düşük',
    'common.critical': 'Kritik',
    'common.normal': 'Normal',
    'common.good': 'İyi',
    'nav.dashboard': 'Ana Sayfa',
    'nav.customerAnalytics': 'Müşteri Analizi',
    'nav.staffManagement': 'Personel Yönetimi',
    'nav.heatmaps': 'Isı Haritaları',
    'nav.queueAnalysis': 'Kuyruk Analizi',
    'nav.reportAnalytics': 'Rapor Analizi',
    'nav.settings': 'Ayarlar',
    'nav.logout': 'Çıkış',
    'nav.userManagement': 'Üyelik Yönetimi',
    'login.title': 'Giriş Yap',
    'login.subtitle': 'AI Destekli Perakende Analiz Platformu',
    'health.checking': 'Sistem durumu kontrol ediliyor...',
    'health.systemActive': 'Sistem Aktif',
    'health.systemError': 'Sistem Hatası',
    'health.connectionFailed': 'Bağlantı kurulamadı',
    'health.title': 'Sistem Sağlık Durumu',
    'health.status': 'Durum',
    'login.username': 'Kullanıcı Adı',
    'login.password': 'Şifre',
    'login.submit': 'Giriş Yap',
    'login.error': 'Giriş başarısız. Lütfen bilgilerinizi kontrol edin.',
    'login.usernamePlaceholder': 'Kullanıcı adınızı girin',
    'login.passwordPlaceholder': 'Şifrenizi girin',
    'login.fillAllFields': 'Lütfen tüm alanları doldurun',
    'login.errorWrongCredentials': 'Kullanıcı adı veya şifre hatalı',
    'login.errorHint': 'Lütfen bilgilerinizi kontrol edin',
    'login.usernameOrEmail': 'Kullanıcı adı veya e-posta',
    'msg.tokenError': 'Token alınamadı',
    'msg.serverError': 'Sunucu hatası',
    'msg.adminAccount': 'Admin hesabı ile giriş yapın',
    'msg.loginFailed': 'Giriş başarısız',
    'dashboard.title': 'Ana Sayfa',
    'dashboard.subtitle': 'Mağaza performansınızın genel görünümü',
    'dashboard.weeklyOverview': 'Mağaza performansınızın haftalık genel görünümü',
    'dashboard.ageDistribution': 'Yaş Dağılımı',
    'dashboard.genderDistribution': 'Cinsiyet Dağılımı',
    'dashboard.avgQueueTime': 'Ort. Kuyruk Süresi',
    'dashboard.busiestCashier': 'En Yoğun Kasa',
    'dashboard.weeklyCustomers': 'Haftalık Müşteri',
    'dashboard.dailyGenderDistribution': 'Günlük Cinsiyet Dağılımı',
    'dashboard.dailyAgeDistribution': 'Günlük Yaş Analizi',
    'dashboard.customersEntered': 'Giren Müşteri',
    'dashboard.customersExited': 'Çıkan Müşteri',
    'dashboard.dailyCustomerFlowTrend': 'Günlük Müşteri Akışı Trendi',
    'dashboard.enteringCustomers': 'Giren Müşteri',
    'dashboard.exitingCustomers': 'Çıkan Müşteri',
    'chart.male': 'Erkek',
    'chart.female': 'Kadın',
    'chart.visitors': 'Ziyaretçiler',
    'chart.total': 'Toplam',
    'chart.new': 'Yeni',
    'chart.returning': 'Geri Dönen',
    'analytics.title': 'Müşteri Sayımı',
    'analytics.subtitle': 'Mağaza içi müşteri sayımı ve giriş-çıkış analizi',
    'analytics.allCameras': 'Tüm Kameralar',
    'analytics.ageDistribution': 'Yaş Dağılımı',
    'analytics.genderDistribution': 'Cinsiyet Dağılımı',
    'analytics.hourlyFlow': 'Saatlik Müşteri Akışı',
    'staffManagement.title': 'Personel Yönetimi',
    'staffManagement.subtitle': 'Gerçek zamanlı personel aktivite izleme ve optimizasyon',
    'heatmaps.title': 'Mağaza Isı Haritaları',
    'heatmaps.subtitle': 'Müşteri hareket ve davranış desenlerinin görsel analizi',
    'heatmap.title': 'Yoğunluk Analizi',
    'heatmap.subtitle': 'Belirli bir günün saatlik bölge yoğunluğunu ve bekleme sürelerini inceleyin.',
    'heatmap.allZones': 'Tüm Bölgeler',
    'heatmap.zone': 'Bölge',
    'heatmap.visitorChange': 'Ziyaretçi Değişimi',
    'heatmap.avgDwell': 'Ort. Bekleme Süresi',
    'heatmap.busiestZone': 'En Yoğun Bölge',
    'heatmap.hourlyDetails': 'Saatlik Performans Detayları (10:00 - 22:00)',
    'heatmap.cancel': 'İptal',
    'heatmap.save': 'Kaydet',
    'heatmap.saving': 'Kaydediliyor...',
    'heatmap.singleZoneEditDisabled': 'Tekil bölge verileri düzenlenemez. Düzenleme yapmak için lütfen "Tüm Bölgeler" filtresini seçin.',
    'heatmap.timeRange': 'Saat Aralığı',
    'heatmap.avgDwellSec': 'Ort. Bekleme (sn)',
    'heatmap.visitorChangeCol': 'Ziyaretçi Değişimi',
    'heatmap.dwellChange': 'Bekleme Süresi Değişimi',
    'heatmap.hourlyVisitorDwell': 'Saatlik Ziyaretçi & Bekleme Süresi (10:00 - 22:00)',
    'heatmap.zonePerformance': 'Bölge Performans Analizi',
    'heatmap.visitorCount': 'Ziyaretçi Sayısı',
    'heatmap.dwellTimeSec': 'Bekleme (sn)',
    'heatmap.avgDwellChart': 'Ort. Bekleme Süresi',
    'heatmap.totalVisitor': 'Toplam Ziyaretçi',
    'heatmap.avgDwellShort': 'Ort. Bekleme',
    'heatmap.loading': 'Veriler Yükleniyor...',
    'heatmap.noData': 'Bu tarih için veri bulunamadı.',
    'queue.title': 'Günlük Kuyruk Analizi',
    'queue.subtitle': 'Belirli bir günün saatlik kuyruk performansını inceleyin.',
    'queue.allCashiers': 'Tüm Kasalar',
    'queue.totalCustomers': 'Toplam Müşteri',
    'queue.avgWait': 'Ortalama Bekleme',
    'queue.maxWait': 'Maksimum Bekleme',
    'queue.hourlyDetails': 'Saatlik Performans Detayları (10:00 - 22:00)',
    'queue.cancel': 'İptal',
    'queue.save': 'Kaydet',
    'queue.saving': 'Kaydediliyor...',
    'queue.singleCashierEditDisabled': 'Tekil kasa verileri düzenlenemez. Düzenleme yapmak için lütfen "Tüm Kasalar" filtresini seçin.',
    'queue.timeRange': 'Saat Aralığı',
    'queue.totalCustomersCol': 'Toplam Müşteri',
    'queue.avgWaitSec': 'Ort. Bekleme (sn)',
    'queue.minWait': 'Min. Bekleme',
    'queue.maxWaitCol': 'Maks. Bekleme',
    'queue.adminOnlyEdit': 'Bu alanı sadece adminler düzenleyebilir.',
    'queue.singleCashierNoEdit': 'Tekil kasa verisi düzenlenemez.',
    'queue.noDataThisSlot': 'Bu saat diliminde düzenlenecek veri yok.',
    'queue.hourlyChart': 'Saatlik Müşteri & Bekleme Süresi (10:00 - 22:00)',
    'queue.waitDistribution': 'Bekleme Süresi Dağılımı',
    'queue.cashierPerformance': 'Kasa Performans Analizi (Tüm Kasalar)',
    'queue.customerCount': 'Müşteri Sayısı',
    'queue.loading': 'Veriler Yükleniyor...',
    'report.title': 'Yapay Zeka Rapor Analizi (Beta)',
    'report.subtitle': 'Yapay Zeka ile verilerinizi analiz edin ve metinsel raporlar oluşturun',
    'report.newAnalysis': 'Yeni Analiz Oluştur',
    'report.selectType': '1. Analiz Türünü Seçin',
    'report.selectDateRange': '2. Tarih Aralığını Seçin',
    'report.customerAnalysis': 'Müşteri Analizi',
    'report.heatmapAnalysis': 'Isı Haritası Analizi',
    'report.queueAnalysis': 'Kuyruk Analizi',
    'report.createAnalysis': 'Analiz Oluştur',
    'report.creatingAnalysis': 'Analiz Oluşturuluyor... (Bu işlem 1 dakika sürebilir)',
    'report.createdAnalyses': 'Oluşturulan Analizler',
    'report.noAnalyses': 'Henüz bir analiz oluşturulmamış.',
    'report.selectTypeAndDate': 'Lütfen analiz türü ve tarih aralığı seçin.',
    'report.errorCreating': 'Analiz oluşturulurken bir hata oluştu.',
    'report.networkError': 'Ağ bağlantı hatası, sunucu çalışıyor mu?',
    'report.completed': 'Tamamlandı',
    'report.processing': 'İşleniyor',
    'report.failed': 'Başarısız',
    'settings.title': 'Ayarlar',
    'settings.subtitle': 'Vislivis deneyiminizi yapılandırın',
    'settings.profileTab': 'Profil',
    'settings.camerasTab': 'Kamera Ayarları',
    'settings.reportingTab': 'Rapor Gönderimi',
    'settings.profileInfo': 'Profil Bilgileri',
    'settings.username': 'Kullanıcı Adı',
    'settings.usernameReadonly': 'Kullanıcı adı değiştirilemez',
    'settings.fullName': 'Ad Soyad',
    'settings.fullNamePlaceholder': 'Adınız Soyadınız',
    'settings.email': 'E-posta',
    'settings.emailPlaceholder': 'ornek@email.com',
    'settings.profileUpdated': 'Profil güncellendi.',
    'settings.updateFailed': 'Güncelleme başarısız.',
    'settings.serverError': 'Sunucuya bağlanılamadı.',
    'settings.saveProfile': 'Profili Kaydet',
    'settings.changePassword': 'Şifre Değiştir',
    'settings.currentPassword': 'Mevcut Şifre',
    'settings.newPassword': 'Yeni Şifre',
    'settings.newPasswordConfirm': 'Yeni Şifre (Tekrar)',
    'settings.updatePassword': 'Şifreyi Güncelle',
    'settings.passwordsMismatch': 'Yeni şifreler eşleşmiyor.',
    'settings.passwordMinLength': 'Yeni şifre en az 6 karakter olmalıdır.',
    'settings.passwordUpdateFailed': 'Şifre değiştirilemedi.',
    'settings.passwordError': 'Sunucuya bağlanırken bir hata oluştu.',
    'settings.cameraFlows': 'Kamera Akışları ve RTSP Bilgileri',
    'settings.setup': 'Kurulum',
    'settings.cameraSetupDesc': 'Kurulum scripti (data_sender_setup.py) ile gönderilen kamera bilgileri burada listelenir.',
    'settings.cameraName': 'Kamera Adı',
    'settings.type': 'Türü',
    'settings.rtspAddress': 'RTSP Adresi',
    'settings.action': 'İşlem',
    'settings.view': 'Görüntüle',
    'settings.noCameras': 'Henüz kamera eklenmemiş. Kurulum scripti ile gönderin.',
    'settings.noImage': 'Görüntü yok',
    'settings.rtspLabel': 'RTSP Adresi',
    'settings.reportRecipients': 'Rapor Gönderim Listesi',
    'settings.reportRecipientsDesc': 'Oluşturulan otomatik raporların gönderileceği e-posta adreslerini buradan yönetebilirsiniz.',
    'settings.addEmailPlaceholder': 'yeni.email@adres.com',
    'settings.add': 'Ekle',
    'settings.currentRecipients': 'Mevcut Alıcılar',
    'settings.noRecipients': 'Henüz alıcı eklenmemiş.',
    'settings.subtitleFull': 'VISLIVIS sistem ayarlarını yönetin',
    'settings.deleteFailed': 'Silme işlemi başarısız oldu.',
    'admin.title': 'Üyelik Yönetimi',
    'admin.subtitle': 'Tüm kullanıcıları görüntüle ve yönet',
    'admin.newUser': 'Yeni Kullanıcı',
    'admin.searchUsers': 'Kullanıcı ara...',
    'admin.user': 'Kullanıcı',
    'admin.role': 'Rol',
    'admin.setup': 'Kurulum',
    'admin.actions': 'İşlemler',
    'admin.goToPanel': 'Panele Git',
    'admin.usersCount': 'kullanıcı',
    'admin.editUser': 'Kullanıcı Düzenle',
    'admin.cameras': 'kamera',
    'admin.sessionExpired': 'Oturum süresi dolmuş. Lütfen tekrar giriş yapın.',
    'admin.leaveEmptyNoChange': 'boş bırak = değişmez',
    'admin.deleteConfirm': 'kullanıcısını silmek istediğinize emin misiniz?',
    'admin.error': 'Hata oluştu',
    'admin.connectionError': 'Bağlantı hatası',
    'admin.brandManager': 'Marka Yöneticisi',
    'admin.managedStores': 'Yönetilen Mağazalar',
    'staff.title': 'Personel Yönetimi',
    'staff.subtitle': 'Personel performansı ve verimlilik analizi',
    'staff.noAuthorization': 'Yetkilendirme yok',
    'staff.totalStaff': 'Toplam Personel',
    'staff.activeStaff': 'Aktif Personel',
    'staff.avgEfficiency': 'Ort. Verimlilik',
    'staff.efficientHours': 'Verimli Saatler',
    'staff.positionDistribution': 'Pozisyon Dağılımı',
    'staff.efficiencyDistribution': 'Verimlilik Dağılımı',
    'staff.staffList': 'Personel Listesi',
    'staff.efficiency': 'Verimlilik',
    'staff.hours': 'Saat',
    'role.admin': 'Yönetici',
    'role.user': 'Kullanıcı',
    'role.storeManager': 'Mağaza Yöneticisi',
    'role.store_manager': 'Mağaza Yöneticisi',
    'role.brandManager': 'Marka Yöneticisi',
    'role.brand_manager': 'Marka Yöneticisi',
    'staff.title': 'Staff Management',
    'staff.subtitle': 'Staff performance and efficiency analysis',
    'staff.noAuthorization': 'No authorization',
    'staff.totalStaff': 'Total Staff',
    'staff.activeStaff': 'Active Staff',
    'staff.avgEfficiency': 'Avg. Efficiency',
    'staff.efficientHours': 'Efficient Hours',
    'staff.positionDistribution': 'Position Distribution',
    'staff.efficiencyDistribution': 'Efficiency Distribution',
    'staff.staffList': 'Staff List',
    'staff.efficiency': 'Efficiency',
    'staff.hours': 'Hours',
  },
  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.noData': 'No data found',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
    'common.custom': 'Custom',
    'common.filters': 'Filters',
    'common.search': 'Search',
    'common.export': 'Export',
    'common.download': 'Download',
    'common.live': 'Live',
    'common.offline': 'Offline',
    'common.online': 'Online',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.critical': 'Critical',
    'common.normal': 'Normal',
    'common.good': 'Good',
    'nav.dashboard': 'Dashboard',
    'nav.customerAnalytics': 'Customer Analytics',
    'nav.staffManagement': 'Staff Management',
    'nav.heatmaps': 'Heatmaps',
    'nav.queueAnalysis': 'Queue Analysis',
    'nav.reportAnalytics': 'Report Analytics',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.userManagement': 'User Management',
    'login.title': 'Login',
    'login.subtitle': 'AI-Powered Retail Analytics Platform',
    'health.checking': 'Checking system status...',
    'health.systemActive': 'System Active',
    'health.systemError': 'System Error',
    'health.connectionFailed': 'Connection failed',
    'health.title': 'System Health Status',
    'health.status': 'Status',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.error': 'Login failed. Please check your credentials.',
    'login.usernamePlaceholder': 'Enter your username',
    'login.passwordPlaceholder': 'Enter your password',
    'login.fillAllFields': 'Please fill all fields',
    'login.errorWrongCredentials': 'Invalid username or password',
    'login.errorHint': 'Please check your credentials',
    'login.usernameOrEmail': 'Username or email',
    'msg.tokenError': 'Token could not be retrieved',
    'msg.serverError': 'Server error',
    'msg.adminAccount': 'Login with admin account',
    'msg.loginFailed': 'Login failed',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your store performance',
    'dashboard.weeklyOverview': 'Weekly overview of your store performance',
    'dashboard.ageDistribution': 'Age Distribution',
    'dashboard.genderDistribution': 'Gender Distribution',
    'dashboard.avgQueueTime': 'Avg. Queue Time',
    'dashboard.busiestCashier': 'Busiest Cashier',
    'dashboard.weeklyCustomers': 'Weekly Customers',
    'dashboard.dailyGenderDistribution': 'Daily Gender Distribution',
    'dashboard.dailyAgeDistribution': 'Daily Age Analysis',
    'dashboard.customersEntered': 'Customers Entered',
    'dashboard.customersExited': 'Customers Exited',
    'dashboard.dailyCustomerFlowTrend': 'Daily Customer Flow Trend',
    'dashboard.enteringCustomers': 'Entering Customers',
    'dashboard.exitingCustomers': 'Exiting Customers',
    'chart.male': 'Male',
    'chart.female': 'Female',
    'chart.visitors': 'Visitors',
    'chart.total': 'Total',
    'chart.new': 'New',
    'chart.returning': 'Returning',
    'analytics.title': 'Customer Count',
    'analytics.subtitle': 'In-store customer count and entrance-exit analysis',
    'analytics.allCameras': 'All Cameras',
    'analytics.ageDistribution': 'Age Distribution',
    'analytics.genderDistribution': 'Gender Distribution',
    'analytics.hourlyFlow': 'Hourly Customer Flow',
    'staffManagement.title': 'Staff Management',
    'staffManagement.subtitle': 'Real-time staff activity monitoring and optimization',
    'heatmaps.title': 'Store Heatmaps',
    'heatmaps.subtitle': 'Visual analytics of customer movement and behavior patterns',
    'heatmap.title': 'Intensity Analysis',
    'heatmap.subtitle': 'View hourly zone intensity and dwell times for a specific day.',
    'heatmap.allZones': 'All Zones',
    'heatmap.zone': 'Zone',
    'heatmap.visitorChange': 'Visitor Change',
    'heatmap.avgDwell': 'Avg. Dwell Time',
    'heatmap.busiestZone': 'Busiest Zone',
    'heatmap.hourlyDetails': 'Hourly Performance Details (10:00 - 22:00)',
    'heatmap.cancel': 'Cancel',
    'heatmap.save': 'Save',
    'heatmap.saving': 'Saving...',
    'heatmap.singleZoneEditDisabled': 'Single zone data cannot be edited. Please select "All Zones" filter to edit.',
    'heatmap.timeRange': 'Time Range',
    'heatmap.avgDwellSec': 'Avg. Dwell (s)',
    'heatmap.visitorChangeCol': 'Visitor Change',
    'heatmap.dwellChange': 'Dwell Time Change',
    'heatmap.hourlyVisitorDwell': 'Hourly Visitors & Dwell Time (10:00 - 22:00)',
    'heatmap.zonePerformance': 'Zone Performance Analysis',
    'heatmap.visitorCount': 'Visitor Count',
    'heatmap.dwellTimeSec': 'Dwell (s)',
    'heatmap.avgDwellChart': 'Avg. Dwell Time',
    'heatmap.totalVisitor': 'Total Visitors',
    'heatmap.avgDwellShort': 'Avg. Dwell',
    'heatmap.loading': 'Loading data...',
    'queue.title': 'Daily Queue Analysis',
    'queue.subtitle': 'View hourly queue performance for a specific day.',
    'queue.allCashiers': 'All Cashiers',
    'queue.totalCustomers': 'Total Customers',
    'queue.avgWait': 'Avg. Wait Time',
    'queue.maxWait': 'Max Wait Time',
    'queue.hourlyDetails': 'Hourly Performance Details (10:00 - 22:00)',
    'queue.cancel': 'Cancel',
    'queue.save': 'Save',
    'queue.saving': 'Saving...',
    'queue.singleCashierEditDisabled': 'Single cashier data cannot be edited. Please select "All Cashiers" filter to edit.',
    'queue.timeRange': 'Time Range',
    'queue.totalCustomersCol': 'Total Customers',
    'queue.avgWaitSec': 'Avg. Wait (s)',
    'queue.minWait': 'Min. Wait',
    'queue.maxWaitCol': 'Max. Wait',
    'queue.adminOnlyEdit': 'Only admins can edit this field.',
    'queue.singleCashierNoEdit': 'Single cashier data cannot be edited.',
    'queue.noDataThisSlot': 'No data to edit for this time slot.',
    'queue.hourlyChart': 'Hourly Customers & Wait Time (10:00 - 22:00)',
    'queue.waitDistribution': 'Wait Time Distribution',
    'queue.cashierPerformance': 'Cashier Performance Analysis (All Cashiers)',
    'queue.customerCount': 'Customer Count',
    'queue.loading': 'Loading data...',
    'queue.noData': 'No data found for this date.',
    'report.title': 'AI Report Analytics (Beta)',
    'report.subtitle': 'Analyze your data with AI and create text reports',
    'report.newAnalysis': 'Create New Analysis',
    'report.selectType': '1. Select Analysis Type',
    'report.selectDateRange': '2. Select Date Range',
    'report.customerAnalysis': 'Customer Analysis',
    'report.heatmapAnalysis': 'Heatmap Analysis',
    'report.queueAnalysis': 'Queue Analysis',
    'report.createAnalysis': 'Create Analysis',
    'report.creatingAnalysis': 'Creating analysis... (This may take 1 minute)',
    'report.createdAnalyses': 'Created Analyses',
    'report.noAnalyses': 'No analyses created yet.',
    'report.selectTypeAndDate': 'Please select analysis type and date range.',
    'report.errorCreating': 'An error occurred while creating analysis.',
    'report.networkError': 'Network connection error. Is the server running?',
    'report.completed': 'Completed',
    'report.processing': 'Processing',
    'report.failed': 'Failed',
    'settings.title': 'Settings',
    'settings.subtitle': 'Configure your Vislivis experience',
    'settings.profileTab': 'Profile',
    'settings.camerasTab': 'Camera Settings',
    'settings.reportingTab': 'Report Sending',
    'settings.profileInfo': 'Profile Information',
    'settings.username': 'Username',
    'settings.usernameReadonly': 'Username cannot be changed',
    'settings.fullName': 'Full Name',
    'settings.fullNamePlaceholder': 'Your full name',
    'settings.email': 'Email',
    'settings.emailPlaceholder': 'example@email.com',
    'settings.profileUpdated': 'Profile updated.',
    'settings.updateFailed': 'Update failed.',
    'settings.serverError': 'Could not connect to server.',
    'settings.saveProfile': 'Save Profile',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.newPasswordConfirm': 'New Password (Confirm)',
    'settings.updatePassword': 'Update Password',
    'settings.passwordsMismatch': 'New passwords do not match.',
    'settings.passwordMinLength': 'New password must be at least 6 characters.',
    'settings.passwordUpdateFailed': 'Could not change password.',
    'settings.passwordError': 'An error occurred while connecting to server.',
    'settings.cameraFlows': 'Camera Streams and RTSP Information',
    'settings.setup': 'Setup',
    'settings.cameraSetupDesc': 'Camera information sent via the setup script (data_sender_setup.py) is listed here.',
    'settings.cameraName': 'Camera Name',
    'settings.type': 'Type',
    'settings.rtspAddress': 'RTSP Address',
    'settings.action': 'Action',
    'settings.view': 'View',
    'settings.noCameras': 'No cameras added yet. Send via setup script.',
    'settings.noImage': 'No image',
    'settings.rtspLabel': 'RTSP Address',
    'settings.reportRecipients': 'Report Recipients List',
    'settings.reportRecipientsDesc': 'Manage the email addresses where automated reports will be sent.',
    'settings.addEmailPlaceholder': 'new.email@address.com',
    'settings.add': 'Add',
    'settings.currentRecipients': 'Current Recipients',
    'settings.noRecipients': 'No recipients added yet.',
    'settings.subtitleFull': 'Manage VISLIVIS system settings',
    'settings.deleteFailed': 'Delete operation failed.',
    'admin.title': 'User Management',
    'admin.subtitle': 'View and manage all users',
    'admin.newUser': 'New User',
    'admin.searchUsers': 'Search users...',
    'admin.user': 'User',
    'admin.role': 'Role',
    'admin.setup': 'Setup',
    'admin.actions': 'Actions',
    'admin.goToPanel': 'Go to Panel',
    'admin.usersCount': 'users',
    'admin.editUser': 'Edit User',
    'admin.cameras': 'cameras',
    'admin.sessionExpired': 'Session expired. Please log in again.',
    'admin.leaveEmptyNoChange': 'leave empty = no change',
    'admin.deleteConfirm': 'Are you sure you want to delete user',
    'admin.error': 'An error occurred',
    'admin.connectionError': 'Connection error',
    'admin.brandManager': 'Brand Manager',
    'admin.managedStores': 'Managed Stores',
    'role.admin': 'Admin',
    'role.user': 'User',
    'role.storeManager': 'Store Manager',
    'role.store_manager': 'Store Manager',
    'role.brandManager': 'Brand Manager',
    'role.brand_manager': 'Brand Manager',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('tr');

  useEffect(() => {
    AsyncStorage.getItem('language').then((lang) => {
      if (lang === 'tr' || lang === 'en') {
        setLanguageState(lang);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
